### ISSUE TITLE
验证码输入后就清空

### ISSUE THREAD

**Issue by ugod3** [JoeshuTT/v-shop#11]
问题重现方式:在注册页面中短信验证码一栏输入数字清空
尝试解决：找跟sms验证码相关的代码，没有找到原因

**Comment by JoeshuTT** [comment]
群加了没，我这没复现出来，说下用的什么系统，浏览器

**Comment by JoeshuTT** [comment]
fix: 输入验证码再聚焦手机号输入会被清空，看看好了么

**Comment by ugod3** [comment]
> fix: 输入验证码再聚焦手机号输入会被清空，看看好了么

已经fix好了吗，我使用了chrome和firefox，用了3.0.1的版本没有发现问题

**Comment by ugod3** [comment]
> fix: 输入验证码再聚焦手机号输入会被清空，看看好了么

3月份的最新版本有我说的输入验证码会清空问题

**Comment by JoeshuTT** [comment]
直接看示例地址访问，没有问题就ok
