### ISSUE TITLE
没看到api工厂的配置方式呢

### ISSUE THREAD

**Issue by LinkLeong** [JoeshuTT/v-shop#7]
rt

**Comment by JoeshuTT** [comment]
他们加官网的帮助中心，有很详细的介绍和使用

**Comment by LinkLeong** [comment]
跟着操作了一下，banner图好像不生效，不知道怎么设置的。

**Comment by JoeshuTT** [comment]
我的加了个标识 indexBaner，你可以去掉或者用自己定义的 都可以

**Comment by LinkLeong** [comment]
不知道在哪修改，你能把数据共享一下吗，我看看怎么设置的。
登录后台，左侧菜单 “工厂设置” --> “数据克隆” --> “将我得数据克隆给别人”

**Comment by LinkLeong** [comment]
感谢，我已经找到了
